stages:
  - tests
  - build
  - release
  - deploy

syntax_test_frontend:
  image: golang:1.12-alpine
  stage: tests
  except:
    - master
  script:
    - cd ui
    - npm install
    - npm run test
  artifacts:
    paths:
      - /root/.npm/_logs/*
    expire_in: 1 week
  allow_failure: true
  
syntax_test_backend:
  image: golang:1.12-alpine
  stage: tests
  except:
    - master
  script:
    - golint -set_exit_status ./...
  allow_failure: true
  
unit_test_backend:
  image: golang:1.12-alpine
  stage: tests
  except:
    - master
  script:
    - export CGO_ENABLED=0
    - export GO_EXTRA_BUILD_ARGS="-a -installsuffix cgo"
    - "go test -timeout 60s -covermode=count -coverprofile count.out ./..."
    - "go tool cover -html=count.out -o coverage.html"
  artifacts:
    paths:
      - coverage.html
    expire_in: 1 week
  allow_failure: true
  
security_test_backend:
  image: golang:1.12-alpine
  stage: tests
  except:
    - master
  script:
    - gosec ./...
  allow_failure: true