stages:
  - build
  - deploy

before_script: 
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    
variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_DEVBRANCH_IMAGE: $CI_REGISTRY_IMAGE:dev
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build_buildserver_branch_image:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - buildserver
  tags:
    - buildserver

build_develop_branch_image:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_DEVBRANCH_IMAGE .
    - docker push $CONTAINER_DEVBRANCH_IMAGE
  only:
    - develop
  tags:
    - buildserver

build_master_branch_image:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
  tags:
    - buildserver

trigger_buildserver_deploy:
  stage: deploy
  script:
    - "curl -X POST -F token=$BUILDSERVERTRIGGER -F ref=buildserver https://gitlab.com/api/v4/projects/13773920/trigger/pipeline"
  only:
    - buildserver
  tags:
    - buildserver

trigger_test_server_deploy:
  stage: deploy
  script:
    - "curl -X POST -F token=$BUILDSERVERTRIGGER -F ref=test.cloud.mxc.org https://gitlab.com/api/v4/projects/13773920/trigger/pipeline"
  only:
    - develop
  tags:
    - buildserver