image: golang:1.12-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - apk add --no-cache ca-certificates make git bash protobuf alpine-sdk nodejs nodejs-npm python

lint_backend:
  stage: test
  script:
    - make lint
  allow_failure: true

syntax_frontend:
  stage: test
  script:
    - make ui/test
  allow_failure: true

unit_tests:
  stage: test
  script:
    - make test
  allow_failure: true

code_coverage:
  stage: test
  script:
    - make coverage
  allow_failure: true

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  allow_failure: true

build:
  stage: build
  script:
    - make
