stages:
  - test
  - build
  - deploy

syntax_test_backend:
  image: golang:1.12-alpine
  stage: test
  before_script: 
    - apk add --no-cache ca-certificates make git bash protobuf protobuf-dev nodejs nodejs-npm
    - go get -u golang.org/x/lint/golint
  script:
    - golint -set_exit_status ./...
  allow_failure: true
  except:
    - buildserver
    - master
    - develop

security_test_backend:
  image: golang:1.12-alpine
  stage: test
  before_script: 
    - apk add --no-cache ca-certificates make git bash protobuf protobuf-dev nodejs nodejs-npm
    - go get github.com/securego/gosec/cmd/gosec
  script:
    - gosec ./...
  allow_failure: true
  except:
    - buildserver
    - master
    - develop
    
variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_DEVBRANCH_IMAGE: $CI_REGISTRY_IMAGE:dev
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build_buildserver_branch_image:
  stage: build
  before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - buildserver
  tags:
    - buildserver

build_develop_branch_image:
  stage: build
  before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_DEVBRANCH_IMAGE .
    - docker push $CONTAINER_DEVBRANCH_IMAGE
  only:
    - develop
  tags:
    - buildserver

build_master_branch_image:
  stage: build
  before_script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
  tags:
    - buildserver

trigger_qa_deploy:
  stage: deploy
  before_script: 
    - apk add --no-cache curl
  script:
    - "curl -X POST -F token=$TRIGGERTOKEN -F ref=$TRIGGERBRANCH https://gitlab.com/api/v4/projects/13773920/trigger/pipeline"
  only:
    - buildserver
  tags:
    - buildserver