run:
  timeout: 5m
  skip-dirs:
    - api/appserver-serves-ui
linters-settings:
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/mxc-foundation
linters:
  enable:
    - gosec
    - gocyclo
    - goimports
    - golint
    - interfacer
    - varcheck
  disable:
    - errcheck
    - unused
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

