files:
  - source: /ui/src/i18n/locales
    ignore:
      - index.js
      - ko.json
      - zhCN.json
      - zhTW.json
      - de.json
      - es.json
      - fr.json
      - ja.json
      - nl.json
      - ru.json
    translation: /ui/src/i18n/locales/%two_letters_code%.json
  - source: /static/templates/email/
      ignore:
        - /**/*?-%two_letters_code%
    translation: /%original_path%/%original_file_name%-%two_letters_code%
