files:
  - source: /ui/src/i18n/locales/en.json
    translation: /ui/src/i18n/locales/%two_letters_code%.json
  - source: /static/templates/email/2fa-login/2fa-login-en
    dest: /static/2fa-login/2fa-login-en.html
    type: html
    translation: /static/2fa-login/2fa-login-%two_letters_code%
  - source: /static/templates/email/2fa-withdraw/2fa-withdraw-en
    dest: /static/2fa-withdraw/2fa-withdraw-en.html
    type: html
    translation: /static/2fa-withdraw/2fa-withdraw-%two_letters_code%
  - source: /static/templates/email/registration-confirm/registration-confirm-en
    dest: /static/registration-confirm/registration-confirm-en.html
    type: html
    translation: /static/registration-confirm/registration-confirm-%two_letters_code%
  - source: /static/templates/email/staking-income/staking-income-en
    dest: /static/staking-income/staking-income-en.html
    type: html
    translation: /static/staking-income/staking-income-%two_letters_code%
  - source: /static/templates/email/topup-confirm/topup-confirm-en
    dest: /static/topup-confirm/topup-confirm-en.html
    type: html
    translation: /static/topup-confirm/topup-confirm-%two_letters_code%
  - source: /static/templates/email/withdraw-success/withdraw-success-en
    dest: /static/withdraw-success/withdraw-success-en.html
    type: html
    translation: /static/withdraw-success/withdraw-success-%two_letters_code%