commit_message: '[ci skip]'
files:
  - source: /ui/src/i18n/locales
    ignore:
      - index.js
      - ko.json
      - zhCN.json
      - zhTW.json
      - de.json
      - es.json
      - fr.json
      - ja.json
      - nl.json
      - ru.json
    translation: /ui/src/i18n/locales/%two_letters_code%.json
  - source: /static/templates/registration-confirm-en
    translation: /static/templates/registration-confirm-%two_letters_code%
