version: "2"
services:
  appserver:
    build: 
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./configuration:/etc/lora-app-server
      - ./:/lora-app-server
    links:
      - postgresql
      - redis
      - mosquitto
    ports:
      - 8080:8080
    environment:
      - APPSERVER=http://localhost:8080
      - MXPROTOCOL_SERVER=http://localhost:4000
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    tty: true

  postgresql:
    image: postgres:9.6-alpine
    volumes:
      - ./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:4-alpine

  mosquitto:
    image: eclipse-mosquitto
