version: "2"
services:
  appserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./configuration:/etc/lora-app-server
    ports:
      - 8080:8080
    environment:
      - APPSERVER=http://localhost:8080
      - MXPROTOCOL_SERVER=http://localhost:4000
