version: "2"
services:
  appserver:
    build: 
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/lora-app-server
    links:
      - postgres
      - redis
      - mosquitto
    tty: true
    ports:
      - 8080:8080

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:4-alpine

  mosquitto:
    image: eclipse-mosquitto
