version: "2"
services:
  appserver:
    build: 
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./configuration:/etc/lora-app-server
      - ./:/lora-app-server
    links:
      - postgresql
      - redis
      - mosquitto
    environment:
      - TEST_POSTGRES_DSN=postgres://loraserver_as:loraserver_as@postgres/loraserver_as?sslmode=disable
      - TEST_REDIS_URL=redis://redis:6379
      - TEST_MQTT_SERVER=tcp://mosquitto:1883
      - LOCAL_HOST_ADDRESS=http://localhost:8080
    ports:
      - 8080:8080
    tty: true

  postgresql:
    image: postgres:9.6-alpine
    volumes:
      - ./.docker-compose/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:4-alpine

  mosquitto:
    image: eclipse-mosquitto
